name: TaxCalc API â€“ CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:

  build_and_test:
    name: Build & Test Kotlin API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Test API
        run: ./gradlew clean test


  docker_build:
    name: Build Docker Image
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t taxcalc-api:latest .

      - name: Verify image starts
        run: docker run --rm taxcalc-api:latest java -version


  publish_image:
    name: Publish Image to GHCR
    needs: docker_build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKENN }}



      - name: Build & Tag Image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$OWNER/taxcalc-api:latest
          docker build -t $IMAGE .

      - name: Push Image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/$OWNER/taxcalc-api:latest
          docker push $IMAGE
#---